# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20171122_1842'),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='login.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(related_name='wishlist_products', to='login.User'),
        ),
    ]
