# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='doh',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='u_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
