# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20171122_1842'),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='login.User')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app2.Wish')),
            ],
        ),
    ]
