# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20171122_1842'),
        ('app2', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='wish',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.AddField(
            model_name='wish',
            name='user',
            field=models.ManyToManyField(related_name='wishes', to='login.User'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
