# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
    ]
