# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20171119_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
