# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_auto_20171119_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
